[package]
name = "how-far"
version = "0.1.0"
edition.workspace = true
rust-version = "1.88"
license.workspace = true
repository.workspace = true
description = "Minimal progress reporting interface for libraries"
keywords = ["progress", "no_std"]
categories = ["concurrency", "no-std"]

[dependencies]
enough = { workspace = true }
